version: '3.1'

services:
  db:
    image: postgres:12-alpine
    ports:
      - 8123:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: begraafregisters
      
  adminer:
    image: adminer
    ports:
      - 8124:8080
